db:
  database: server.db
  host: ./
  pool_size: 10
  type: sqllite
ext:
  cpu_infer: 46
log:
  backup_count: -1
  dir: logs
  file: lexllama.log
  level: debug
model:
  device: cuda:0
  gguf_path: /mnt/data/model/DeepSeek-Coder-V2-GGUF-WJH/
  name: DeepSeek-Coder-V2-Instruct
  path: /mnt/data/model/DeepSeek-Coder-V2-Instruct/
  type: ktransformers
server:
  ip: 0.0.0.0
  port: 12456
user:
  algorithm: HS256
  secret_key: 981f1dd2a44e27d68759d0252a486568ed43480b4e616a26e3af3709c3a7ce73
web:
  mount: false
  open_cross_domain: true
